name: market-returns
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-forge::dash
  - conda-forge::dash-bootstrap-components
  - gunicorn
  - httpx
  - lxml
  - numba
  - pandas
  - pip
  - plotly
  - defaults::python=3.12
  - requests
  - python-calamine
  - yfinance
  - pip:
      - fredapi
