name: market-returns
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-forge::dash
  - gunicorn
  - lxml
  - numba
  - openpyxl
  - pandas
  - pip
  - plotly
  - python=3.11
  - requests
  - xlrd
  - pip:
      - fredapi
      - yahooquery
