[project]
name = "stock-market-returns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.15"
dependencies = [
    "dash-bootstrap-components>=2.0.4",
    "dash[compress]>=4.4.1",
    "curl-cffi>=0.16.2",
    "plotly>=7.0.0",
    "scipy>=1.18.1",
    "yfinance>=1.7.0",
    "polars>=1.44.1",
    "fastexcel>=0.21.0",
    "lxml>=6.1.2",
    "numba>=0.67.0",
    "orjson>=3.12.0",
    "pydantic>=2.13.5",
    "beautifulsoup4>=4.15.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "nbformat>=5.11.1",
    "prek>=0.5.0",
    "pyright>=1.1.411",
    "ruff>=0.16.5",
    "selenium>=4.48.0",
    "snakeviz>=2.2.2",
]
prod = [
    "gunicorn>=26.0.0",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "standard"
